language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
          
script:
 - pip install -r python/requirements.txt
 - export PYTHONPATH=.
 - pytest python/test_pythonEvaluator.py
 - pytest python/test_areplDump.py
 - python -m python.stdlib_list.stdlibTest

cache:
  directories:
    - ~/.npm
    
after_success:
  - npm ci
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
