language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: bionic
          sudo: true
        - python: 3.8
          dist: bionic
          sudo: true
          
before_script: cd python
script:
 - pip install -r requirements.txt
 - pytest
after_script: cd ../

cache:
  directories:
    - ~/.npm
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm ci
  - npm run compileOnce
  - npm run travis-deploy-once "npm run semantic-release" # todo: replace deploy-once with https://docs.travis-ci.com/user/build-stages/
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
