language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

addons:	
  apt:	
    packages:	
      - freeglut-devel # needed for p5 otherwise it gets:  ImportError: Library "GLU" not found

before_script:
    # xvfb is needed for the p5 test
  - "Xvfb :99 -screen 0 1400x900x24 > /dev/null 2>&1 &"
  - sleep 3 # give xvfb some time to start
          
script:
 - pip install -r python/requirements.txt
 - pytest python/test_pythonEvaluator.py
 - pytest python/test_arepldump.py
 - python -m python.stdlib_list.stdlibTest

cache:
  directories:
    - ~/.npm
    
after_success:
  - npm ci
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
