language: python
matrix:
    include:
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: pypy
          dist: trusty
          sudo: false
script:
 - python python/pythonEvaluatorTest.py
 - python python/arepldumptest.py
 - python -m python.stdlib_list.stdlibTest
