[tool.black]
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | python/arepl_jsonpickle 
    # jsonpickle is excluded as this isnt controlled by us
    # it is hardcoded into the repo but technically a seperate package
  )/
)
'''